### ISSUE TITLE
Using Terminal=true in a Desktop file starts terminal in XFCE

### ISSUE THREAD

**Issue by hphilm** [oberon2007/ff-theme-util#1]
It is a little ugly, that the script starts in a terminal:

![issue-ff](https://user-images.githubusercontent.com/5050022/27374052-bc1aa340-566a-11e7-92a5-2dc647383510.png)

**Comment by oberon-manjaro** [comment]
fixed in https://github.com/oberon2007/ff-theme-util/commit/87cf12bfd57c9c5f2d71fafc1ced60404a508de9
